### ISSUE TITLE
Unable to run demo.py without HumanML3D dataset

### ISSUE THREAD

**Issue by lzyplayer** [ChenFengYe/motion-latent-diffusion#23]
Thanks for such great work!
And congratulations on the paper being accepted!
I follow the instruction However I cannot run the demo script with the given parameters.

Do I have to download the HumanML3D dataset to try the demo?

**Comment by ChenFengYe** [comment]
Currently, the code is related to this dataset. However, it does not need this dataset for the demo technically.
We will provide a revised version to remove the dataset dependency of the demo.
You can also remove this by modifying the code.

**Comment by lzyplayer** [comment]
Thanks for your kindly reply!

**Comment by zhLawliet** [comment]
> We will provide a revised version to remove the dataset dependency of the demo.
have you provided the code?

**Comment by lzyplayer** [comment]
Currently, I just downloaded and setup the dataset to run just the inference part.
