### ISSUE TITLE
I have obtained R-precision test results, but they differ from those reported in the paper.

### ISSUE THREAD

**Issue by hangaoge** [ChenFengYe/motion-latent-diffusion#27]
![_20230411162947](https://user-images.githubusercontent.com/112455033/231102665-c3bb2492-bc96-455b-a779-1c261eeef95a.png)

![20230411163110](https://user-images.githubusercontent.com/112455033/231102794-5f34cbec-ad09-4b9b-9bbf-13c09f572765.png)

**Comment by hangaoge** [comment]
I have not modified any hyperparameters.

**Comment by hangaoge** [comment]
The other results are consistent.

**Comment by hangaoge** [comment]
I‘m sorry that i modified the R_size.

**Comment by ChenFengYe** [comment]
All right. If you have any other concerns, please let me know.
