### ISSUE TITLE
About the encode part of VAE

### ISSUE THREAD

**Issue by FortisCK** [ChenFengYe/motion-latent-diffusion#28]
I used the model for another task, about 3D faces. After training the VAE part, the generated results are basically static. The structure of the data is similar, it is [batch, nframes, vertices], I am wondering why only the length of dist.shape[0] is taken here, how to reconstruct the information of each frame after the data is encoded to [batch, 1, 256]?
我将模型用在了另一个任务上，是关于3D人脸。训练好VAE部分后，生成的结果基本是静态的。数据的结构差不多，是[batch, nframes, vertices]，我在想为什么这里要只取dist.shape[0]的长度，数据被压缩到[batch, 1, 256]后如何还原每一帧的信息呢？
https://github.com/ChenFengYe/motion-latent-diffusion/blob/c28a06435077800fde4d76ef93eb2a4016a5120c/mld/models/architectures/mld_vae.py#L164

**Comment by ChenFengYe** [comment]
Nice problem! It is a vae-style network. [1, 256] is a global feature (distribution of the motion clip), and other tokens are abundant. If you read the paper ACTOR, the design is similar to their framework. You do not need all tokens to get the distribution parameters (latent). We also try to extend the latent size [1,256]=>[7,256], however, the results are not that great. We have explained in the github page "MLD-1 VS MLD-7". Moreover, the latent can share the motion information in the decoder part, where each frame can be recovered.

你好，VAE模型一般需要，中间是个小尺寸特征来增加学习难度，同时，也能增强范化性。另外，这个小尺寸特征也可以加速整个动作生成网络（减少计算量），这不表示只用第一帧的特征，因为transformer本身就是全局计算的，不像CNN是local的。这点设计也与ACTOR的transformerVAE结构相近，这个特征是用来表征整个动作片段。我们也试过更大尺度的比如[7,256]。论文里也有，但是提升效果没有那么显著，个人觉得是数据量的问题，目前的动作数据集太小，github主页也有相关内容可以参考"MLD-1 VS MLD-7". 
既然是“全局latent”，decode时就能从中回复每帧信息了。
你说的生成结果是静态的问题，我之前也遇到过，训练MDM时，也遇到过（我个人感觉就是因为没训练好），建议你调整下网络learning rate等等超参，另外检查下数据。MDM也有类似提问，可以参考下。
https://github.com/GuyTevet/motion-diffusion-model/issues/54
https://github.com/GuyTevet/motion-diffusion-model/issues/104
