### ISSUE TITLE
How to pretrain VAE?

### ISSUE THREAD

**Issue by linjing7** [ChenFengYe/motion-latent-diffusion#3]
Hi, thanks for your excellent work. As mentioned in the paper, the training process includes VAE training stage and diffusion training stage. But it seems that there is only one stage in the instruction of README. How do you perform the VAE pre-training?

**Comment by ChenFengYe** [comment]
Thanks for your attention! The current version also supports the VAE training stage. If you want to train your own VAE model, please refer to https://github.com/ChenFengYe/motion-latent-diffusion/blob/main/configs/config_vae_humanml3d.yaml

We will also consider to provide more specific instructions soon.

**Comment by linjing7** [comment]
Okay, thank you very much!

**Comment by linjing7** [comment]
Hi, can I train the VAE with the following command?
`python -m train --cfg configs/config_vae_humanml3d.yaml --cfg_assets configs/assets.yaml --batch_size 64`

**Comment by ChenFengYe** [comment]
That's right. If you find more issues, please let me know.

**Comment by linjing7** [comment]
@ChenFengYe Hi, I have successfully trained VAE with the above command. In the diffusion training stage, do I need to load the pretrtaiend VAE before training? That is, change the `"PRETRAINED_VAE"` in `config_mld_humanml3d.yaml` to the path of the pretrained VAE model.

**Comment by ChenFengYe** [comment]
That's right. After training your own VAE models, you can specify the PRETRAINED_VAE with your VAE.

**Comment by linjing7** [comment]
Okay, thank you very much.
