### ISSUE TITLE
how can i use smpl rot6d motion_representation for motion reconstruct

### ISSUE THREAD

**Issue by jihg88** [ChenFengYe/motion-latent-diffusion#30]
I tried using humanact12 pretrain_model with the following command
"--cfg" ,"./configs/config_mld_humanact12.yaml", "--cfg_assets", "./configs/assets.yaml", "--task", "reconstrucion"
But an error is reported when calling this function "self.feats2joints" which is defined  in mld.py line 132,because a parameter ”mask“ is missing in mld.py line 285.

**Comment by ChenFengYe** [comment]
Hi, thanks for your attention. The line 285 of mld.py does not include "mask" parameters.
https://github.com/ChenFengYe/motion-latent-diffusion/blob/af507c479d771f62a058b5b6abb51276b36d6c6d/mld/models/modeltype/mld.py#L285

If you want to use smpl rot6d, you need to remove this ``self.feats2joints``. It is used to convert features into xyz joints.
If you are familiar with SMPL, you can use its joint regressor to replace ``self.feats2joints`` directly.

**Comment by jihg88** [comment]
Thank you for your reply！I see, if I just want the result in SMPL rot_6d form,  this "feats_rst = self.vae.decode(z, length)" in line 282 is all i need.
