### ISSUE TITLE
Is this result as expected?

### ISSUE THREAD

**Issue by zhLawliet** [ChenFengYe/motion-latent-diffusion#31]
The results were found to be very unstable,  Is this result as expected?
when i write those in exmple.txt
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.
120 a person kicks something with his right leg.

the results:
![Example_120_batch0_0](https://user-images.githubusercontent.com/17424385/234556750-2be6df1c-9132-44ec-9717-296d12e589ce.gif)
![Example_120_batch0_1](https://user-images.githubusercontent.com/17424385/234556838-3641c728-0df6-443d-9e4a-c236f7e47928.gif)
![Example_120_batch0_2](https://user-images.githubusercontent.com/17424385/234556858-8dd954b4-f7d9-4a7e-8aa1-5e0436fff6ab.gif)
![Example_120_batch0_2](https://user-images.githubusercontent.com/17424385/234556780-eea18c06-3723-4e3a-b859-e64231368ba4.gif)
.....

**Comment by ChenFengYe** [comment]
Hi, does your "unstable" means the results are not deterministic? This is a diffusion model, which means the same input can generate diverse motion results. If you want to make it deterministic, you can just fix the seed like below. Moreover, the deme.txt is for one batch forward (init noises for each instance are also different), so it could still generate different results.
https://github.com/ChenFengYe/motion-latent-diffusion/blob/7db8623e61e2b6818e724a0a9a1fc999f5054327/mld/utils/fixseed.py#L6

If the unstable means the model can not generate the correct right legs, we shall admit our model still need improvements. Anyway, the quality of your results is close to our testing.

**Comment by zhLawliet** [comment]
@ChenFengYe 谢谢回复，这里的“ unstable”指的是这里居然左右（left和right）都没法稳定的区分，10个sampe存在4个都是左脚。我理解这里面的结果至少都保障是右脚进行踢（毕竟left和right应该是训练集里面非常常见的单词），所以想确认一下我这边对于left和right的区分稳定性跑出来的结果符合你那边的预期？至于怎么踢，这里存在多样式可以理解。
