### ISSUE TITLE
how to change the length of the motion?

### ISSUE THREAD

**Issue by ShungJhon** [ChenFengYe/motion-latent-diffusion#36]
您好，请问example.txt 开头的数字是代表什么？是帧数吗？
还有想问一下模型里，如何控制生成的总长度。还是这个长度是每一次生成的过程中随机采样的结果吗？

**Comment by ChenFengYe** [comment]
是的，就是指输出的帧数，模型里，生成长度也是通过这个length变量来控制，长度并不是算法随机生成的，而是制定输入的。
另外，你可以参考这里，有些关于生成长度的解释。
https://github.com/ChenFengYe/motion-latent-diffusion/blob/c28a06435077800fde4d76ef93eb2a4016a5120c/README.md?plain=1#L215

**Comment by ShungJhon** [comment]
感谢您的回答。也就是说这个时间长度只用在了vae的decoder部分是吗，扩散模型denoiser的部分就没有用到过

**Comment by ChenFengYe** [comment]
是的 diffusion过程中没用到，用的是全局的global latent
