### ISSUE TITLE
git lfs issue

### ISSUE THREAD

**Issue by mmdrahmani** [ChenFengYe/motion-latent-diffusion#4]
Hi Chen
Thanks for the excellent work.
I was trying to use the demo:
`python demo.py --cfg ./configs/config_mld_humanml3d.yaml --cfg_assets ./configs/assets.yaml --example ./demo/example.txt`
But I got this error:
`You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run git lfs install followed by git lfs pull in the folder you cloned.`
The error happens at this line:
`self.text_model = AutoModel.from_pretrained(modelpath)`

I installed git lfs, both before and after cloning the mld repository. But I still get the error related to git lfs. Any ideas what might be wrong?

**Comment by mmdrahmani** [comment]
Well, it seems that I had to run all the files in the prepare folder. Now it works. So I close this issue.

**Comment by yinkangning0124** [comment]
Hi, I am facing the same problem. Do you mean that after manually installed git lfs, I have to run the scripts in the prepare fold again?

**Comment by mmdrahmani** [comment]
Hi. As far as I remember, you only need run the scripts in the prepare folder. If you manually installed git-lfs in the environment, then just run all the prepare documents.

**Comment by yinkangning0124** [comment]
> 

Yeah, I solved this. Thanks a lot!

**Comment by lzyplayer** [comment]
If someone still sees it, you need to execute the script in the prepare folder in the project root directory, otherwise, it will download the file to the prepare directory
