### ISSUE TITLE
About the prior in mld.py and memory in mld_denoiser

### ISSUE THREAD

**Issue by 1994cxy** [ChenFengYe/motion-latent-diffusion#48]
I am confused by the two parts in the diffusion process.

(1) In mld.py, line 460 and 461, the noise and noise_pred were chunked in to two-part to get the noise_prior and noise_pred_prior. What is the meaning of the prior? I am not very familiar with diffusion, and for me, it seems like all I need to do is calculate the MSE between noise and noise_pred.
(2) In mld_denoiser.py, line 216, the decoder uses "tgt" and "memory" to compute the output. What is the meaning of tgt and memory?

**Comment by ChenFengYe** [comment]
Hi 1994cxy,  
1) This chunking trick (two parts) is for classifer_free_guidance, an inference process of diffusion.
https://github.com/ChenFengYe/motion-latent-diffusion/blob/081ce3152e5a95b14a4495fb2d32939c257c6216/mld/models/modeltype/mld.py#L460
https://github.com/ChenFengYe/motion-latent-diffusion/blob/081ce3152e5a95b14a4495fb2d32939c257c6216/mld/models/modeltype/mld.py#L339

2) It is a MSE loss for noise and noise_pred.
3) tgt and memory  indicate two inputs of the transformer module.  You can refer to this link for details.
https://blog.csdn.net/zhaohongfei_358/article/details/126019181

**Comment by 1994cxy** [comment]
very helpful, thanks a lot.
