### ISSUE TITLE
Fail to load DDIMScheduler

### ISSUE THREAD

**Issue by xiezhy6** [ChenFengYe/motion-latent-diffusion#6]
Hi, thanks for releasing your excellent work!

When I try to train the second stage (i.e., mld module), I fail to load the DDIMScheduler. When I look into the config file `./configs/modules/scheduler.yaml`，I think the definition of DDIMScheduler might be in some file under the directory `diffusers`. However, I can find this directory in the root directory of the project.  So, do I miss anything? Could you please tell me where the definition of DDIMScheduler is?

Thanks!

**Comment by ChenFengYe** [comment]
Hi, [diffusers](https://github.com/huggingface/diffusers) is a python library. 

> Diffusers provides pretrained diffusion models across multiple modalities, such as vision and audio, and serves as a modular toolbox for inference and training of diffusion models.


You can install it using:
```
conda activate mld
pip install diffusers
(suggested) pip install diffusers==0.7.2
```
It has been included in https://github.com/ChenFengYe/motion-latent-diffusion/blob/98c97c00d63757cf9da9f1dc4afc473dc3faf928/requirements.txt#L23
```
pip install -r requirements.txt
```
If this can't solve your problem, please tell us and provide your log or errors.

**Comment by xiezhy6** [comment]
Thanks! It works for me.
